# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingFormat',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('function', models.CharField(choices=[(b'md5', b'pVault_MD5'), (b'salted_md5', b'pVault_Salted_MD5'), (b'ntlm', b'pVault_NTLM')], max_length=33)),
                ('example', models.CharField(blank=True, help_text=b"codes a 'hello!' string", max_length=128, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Encoding formats',
            },
        ),
        migrations.CreateModel(
            name='PasswordEncoding',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('iv', models.CharField(blank=True, max_length=256, null=True)),
                ('secret', models.CharField(blank=True, max_length=256, null=True)),
                ('salt', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('encoding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pVault.EncodingFormat')),
            ],
            options={
                'verbose_name_plural': 'Password Encoding',
            },
        ),
        migrations.CreateModel(
            name='PasswordVault',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=135)),
                ('password', models.CharField(help_text=b'this will be filled with encrypted password encoded as hexlified string', max_length=1024)),
                ('description', models.CharField(blank=True, max_length=135, null=True)),
                ('is_active', models.BooleanField()),
                ('exported_to_servers', models.BooleanField()),
            ],
            options={
                'ordering': ['username'],
                'verbose_name_plural': 'Password Vault (users credentials)',
            },
        ),
        migrations.CreateModel(
            name='PasswordVaultExports',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('password_encoding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pVault.PasswordEncoding')),
                ('password_vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pVault.PasswordVault')),
            ],
            options={
                'verbose_name_plural': 'Password Vault exports',
            },
        ),
        migrations.CreateModel(
            name='PasswordVaultHistory',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('password_vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pVault.PasswordVault')),
            ],
            options={
                'verbose_name_plural': 'Password Vault history',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id_tab', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=135)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField()),
                ('ip', models.CharField(max_length=46, verbose_name=b'hostname')),
                ('worker_queue', models.CharField(blank=True, help_text=b'the running worker on the server listens to this queue, if needed', max_length=46, null=True)),
                ('password_encoding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pVault.PasswordEncoding')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.AddField(
            model_name='passwordvault',
            name='export_to_servers',
            field=models.ManyToManyField(blank=True, null=True, to='pVault.Server'),
        ),
    ]
